version: '3.8'

services:
  rabbit:
    image: 'rabbitmq:3-management'
    env_file:
      - .env
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - fun-net
  
  pgdb-sensors:
    image: pgdb-sensors
    build:
      context: ./pgdb-sensors
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - fun-net

  pgdb-sensors-adminer:
    image: adminer
    restart: always
    ports:
      - 10000:8080
    networks:
      - fun-net

networks:
  fun-net:
    driver: bridge  